/**
 * Schema-drift contract test (TS side).
 *
 * Pairs with `optimizer-service/tests/test_schema_contract.py` to lock
 * down the three sources of truth for AutoScheduler input shapes:
 *
 *   1. Pydantic models in `ortools_runner.py` (HTTP boundary)
 *   2. Dataclass models in `model_builder.py`  (solver internals)
 *   3. TypeScript interfaces in `scheduling/types.ts` (browser)
 *
 * The pydantic-side schema is dumped to
 * `optimizer-service/schema-snapshot.json` by
 * `optimizer-service/scripts/dump_schema.py`. This test loads that
 * snapshot and asserts every field exists on the corresponding TS
 * interface (and vice versa).
 *
 * Workflow when this test fires:
 *   - if pydantic added a field: mirror it in the TS interface,
 *     then re-run `python scripts/dump_schema.py` and commit the
 *     refreshed snapshot.
 *   - if the TS interface added a field: mirror in pydantic +
 *     dataclass, regenerate the snapshot, and the existing pytest
 *     contract test will confirm the dataclass side too.
 *
 * Browser-only fields that intentionally don't cross the wire are
 * listed in BROWSER_ONLY_FIELDS below.
 */
import { describe, expect, it } from 'vitest';
// Snapshot is generated by `optimizer-service/scripts/dump_schema.py`.
// Vite's JSON import gives us a typed object — keys are snapshot type
// names, values are sorted field-name arrays.
import schemaSnapshot from '../../../../optimizer-service/schema-snapshot.json';
import type {
    OptimizerShift,
    OptimizerEmployee,
    OptimizerConstraints,
    OptimizerStrategy,
    AvailabilitySlotRef,
    ExistingShiftRef,
} from '../types';

// ---------------------------------------------------------------------------
// Helpers — turn an interface keyof into a runtime Set via a typed sample.
//
// TS interfaces are erased at runtime, so we can't reflect over them
// directly. The convention here is to declare a sample object typed
// `Required<T>` that lists EVERY field by name. The `Required<>`
// makes optional fields visible to keyof.
//
// Adding a new field to the interface forces a TS error here until
// the sample is updated — exactly the kind of drift we want to surface
// at compile time.
// ---------------------------------------------------------------------------

function fieldSet<T>(sample: { [K in keyof T]: unknown }): Set<string> {
    return new Set(Object.keys(sample));
}

// Each sample below MUST list every field of the corresponding type.
// `Required<T>` strips optionals so missing fields produce a TS error.

const SHIFT_FIELDS = fieldSet<Required<OptimizerShift>>({
    id: 0, shift_date: 0, start_time: 0, end_time: 0, duration_minutes: 0,
    role_id: 0, required_skill_ids: 0, required_license_ids: 0,
    priority: 0, demand_source: 0, target_employment_type: 0,
    target_requires_flexible: 0, level: 0,
    is_sunday: 0, is_saturday: 0, is_public_holiday: 0, is_training: 0,
    unpaid_break_minutes: 0, shift_type: 0,
});

const EMPLOYEE_FIELDS = fieldSet<Required<OptimizerEmployee>>({
    id: 0, name: 0, role_id: 0, contracted_role_ids: 0, contract_type: 0, employment_type: 0,
    hourly_rate: 0, min_contract_minutes: 0, contract_weekly_minutes: 0,
    max_weekly_minutes: 0, skill_ids: 0, license_ids: 0,
    preferred_shift_ids: 0, unavailable_dates: 0, level: 0,
    is_flexible: 0, is_student: 0, visa_limit: 0,
    existing_shifts: 0, contracts: 0, qualifications: 0,
    availability_slots: 0, has_availability_data: 0,
    availability_mode: 0,
    // HC-5e contract ordinary-hours envelope. Declared on BOTH sides or Pydantic
    // drops it at the wire boundary and the envelope silently stops binding —
    // which for an FT, who carries no availability slots, means available 24/7.
    ordinary_span_start: 0, ordinary_span_end: 0, ordinary_days: 0,
    availability_overrides: 0, fairness_debts: 0,
    initial_effective_minutes: 0,
    // Schedule 3/4/5/6 classification carriers. These had drifted out of this
    // sample — the `Required<T>` trick was raising TS2554 the whole time, but
    // the repo's `type-check` script points at the root tsconfig, which has
    // `"files": []` and only project references, so `tsc --noEmit` compiled
    // NOTHING and the drift was never surfaced. Run
    // `tsc -p tsconfig.app.json --noEmit` to actually type-check the app.
    is_security_role: 0,
    is_apprentice: 0, apprentice_type: 0, apprentice_year: 0, has_completed_year_12: 0,
    is_trainee: 0, trainee_category: 0, trainee_level: 0, trainee_exit_year: 0,
    trainee_years_out: 0, trainee_aqf_level: 0, trainee_year: 0,
    is_training_on_job: 0, prefers_sba_loading: 0,
    is_sws: 0, sws_capacity_percentage: 0,
});

const CONSTRAINTS_FIELDS = fieldSet<Required<OptimizerConstraints>>({
    min_rest_minutes: 0, enforce_role_match: 0, enforce_skill_match: 0,
    allow_partial: 0, relax_constraints: 0, enforce_availability: 0,
});

const STRATEGY_FIELDS = fieldSet<Required<OptimizerStrategy>>({
    fatigue_weight: 0, fairness_weight: 0, cost_weight: 0, coverage_weight: 0,
});

const AVAILABILITY_SLOT_FIELDS = fieldSet<Required<AvailabilitySlotRef>>({
    slot_date: 0, start_time: 0, end_time: 0,
});

const EXISTING_SHIFT_FIELDS = fieldSet<Required<ExistingShiftRef>>({
    id: 0, shift_date: 0, start_time: 0, end_time: 0,
    duration_minutes: 0, unpaid_break_minutes: 0,
});

// ---------------------------------------------------------------------------
// Browser-only fields that intentionally don't cross the wire
// ---------------------------------------------------------------------------

const BROWSER_ONLY_FIELDS: Record<string, Set<string>> = {
    // `contract_type` is the TS frontend enum ('FT'|'PT'|'CASUAL'); the
    // backend uses `employment_type` ('FT'|'PT'|'Casual'). Controller
    // maps between them. Keeping both in TS for backwards compat.
    Employee: new Set([
        'contract_type', 'contracts', 'qualifications',
        // Schedule 4/5/6 WAGE classification. The CP-SAT solver has no
        // apprentice/trainee/SWS wage model — only a flat `hourly_rate` — so
        // these deliberately do not cross the wire. They are consumed solely by
        // the greedy fallback's own cost re-estimate, which implements
        // Schedule 4/5/6 in full. See the OptimizerEmployee doc comment.
        //
        // `is_security_role` USED TO BE LISTED HERE, and should never have been.
        // It sat among the wage carriers under a comment about the solver having
        // no wage model, which is true of apprentices and trainees and false of
        // this flag: Schedule 3 §3.1 makes it a CONSTRAINT discriminator, setting
        // a full-time Security employee's work cycle to 8 weeks at 42h/week
        // instead of 4 weeks at 38h. The controller had been populating it all
        // along; the wire dropped it, so the solver sized every Security roster
        // against the general envelope and could never produce the roster the
        // labour layer would have accepted. It now crosses.
        'is_apprentice', 'apprentice_type', 'apprentice_year', 'has_completed_year_12',
        'is_trainee', 'trainee_category', 'trainee_level', 'trainee_exit_year',
        'trainee_years_out', 'trainee_aqf_level', 'trainee_year',
        'is_training_on_job', 'prefers_sba_loading',
        'is_sws', 'sws_capacity_percentage',
    ]),
    // `demand_source` is a frontend filter hint ('baseline' vs ML-
    // predicted) used to scale shift priority before sending. Not in
    // pydantic.
    Shift: new Set(['demand_source']),
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

interface PairCase {
    name: string;
    snapshotKey: keyof typeof schemaSnapshot;
    tsFields: Set<string>;
}

const PAIRS: PairCase[] = [
    { name: 'Shift', snapshotKey: 'Shift', tsFields: SHIFT_FIELDS },
    { name: 'Employee', snapshotKey: 'Employee', tsFields: EMPLOYEE_FIELDS },
    { name: 'ExistingShift', snapshotKey: 'ExistingShift', tsFields: EXISTING_SHIFT_FIELDS },
    { name: 'AvailabilitySlot', snapshotKey: 'AvailabilitySlot', tsFields: AVAILABILITY_SLOT_FIELDS },
    { name: 'Constraints', snapshotKey: 'Constraints', tsFields: CONSTRAINTS_FIELDS },
    { name: 'Strategy', snapshotKey: 'Strategy', tsFields: STRATEGY_FIELDS },
];

describe('Optimizer schema contract — TS interfaces ↔ Python pydantic', () => {
    for (const { name, snapshotKey, tsFields } of PAIRS) {
        it(`${name}: TS interface and pydantic share field names`, () => {
            const snapshot = new Set(schemaSnapshot[snapshotKey]);
            const browserOnly = BROWSER_ONLY_FIELDS[name] ?? new Set<string>();

            const onlyInTs = [...tsFields].filter(f => !snapshot.has(f) && !browserOnly.has(f));
            const onlyInPython = [...snapshot].filter(f => !tsFields.has(f));

            expect(onlyInTs, `[${name}] TS-only fields (mirror in pydantic OR add to BROWSER_ONLY_FIELDS): ${onlyInTs.join(', ')}`).toEqual([]);
            expect(onlyInPython, `[${name}] Python-only fields (mirror in TS interface): ${onlyInPython.join(', ')}`).toEqual([]);
        });
    }
});
