/**
 * CPI increase projection + export (Phase-2 rate admin, pure — no I/O).
 *
 * ICC Sydney EA 2025 cl 25.1 mandates a CPI + 0.5% wage/allowance increase from
 * the first pay period on or after 1 July 2026, 2027 and 2028. This module takes
 * a base `EbaRateSet` (as read from the DB) plus a published CPI% and projects
 * the next effective-dated set, then emits the two artefacts an engineer applies:
 *
 *   1. the `INSERT` SQL for a new migration (durable DB source of truth), and
 *   2. the one-line `RATE_SCHEDULE.push(applyCpiIncrease(...))` TS snippet for the
 *      embedded copy the worker cost engine reads.
 *
 * WHY EMIT, NOT WRITE: the worker engine can't read the DB at runtime, so the TS
 * copy must be updated in code and redeployed; and RLS denies authenticated
 * writes to eba_rate anyway. Emitting both keeps the DB ⇄ TS drift guard
 * (rate-schedule-sync.test.ts) satisfied — the per-value rounding here matches
 * `applyCpiIncrease`'s `r2`, so the generated SQL and the TS helper agree.
 */

import type { EbaRateSet, EbaRateRow, EbaAllowanceRow } from '../data/ebaRates.read.api';

/** Round to cents — identical to rate-schedule.ts `r2`. */
export const round2 = (x: number): number => Math.round(x * 100) / 100;

/** cl 25.1 multiplier: CPI% + 0.5%. */
export const cpiFactor = (cpiPercent: number): number => 1 + (cpiPercent + 0.5) / 100;

export interface CpiProjectionInput {
  base: EbaRateSet;
  /** ABS All-Groups CPI (Sydney), March-quarter YoY % (cl 25.2). */
  cpiPercent: number;
  /** Effective date of the new set (YYYY-MM-DD), e.g. '2026-07-01'. */
  effectiveFrom: string;
}

export interface CpiProjection {
  effectiveFrom: string;
  cpiPercent: number;
  factor: number;
  rates: EbaRateRow[];
  allowances: EbaAllowanceRow[];
}

/**
 * Project the next effective-dated set from `base` by applying CPI + 0.5% to
 * every rate and allowance (rounded to cents, each value independently). Pure —
 * never mutates `base`.
 */
export function projectCpiIncrease({ base, cpiPercent, effectiveFrom }: CpiProjectionInput): CpiProjection {
  const factor = cpiFactor(cpiPercent);
  const rates: EbaRateRow[] = base.rates.map((r) => ({
    classification: r.classification,
    employmentBasis: r.employmentBasis,
    ordinaryHourlyRate: round2(r.ordinaryHourlyRate * factor),
    paidHourlyRate: round2(r.paidHourlyRate * factor),
    source: r.source,
  }));
  const allowances: EbaAllowanceRow[] = base.allowances.map((a) => ({
    code: a.code,
    amount: round2(a.amount * factor),
    unit: a.unit,
    source: a.source,
  }));
  return { effectiveFrom, cpiPercent, factor, rates, allowances };
}

const q = (s: string | null): string => (s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`);
const money = (n: number): string => n.toFixed(2);

/**
 * Emit the migration SQL that inserts the projected set into eba_rate +
 * eba_allowance. Idempotent (ON CONFLICT DO NOTHING), matching the baseline
 * migration's convention. The `source` column records the CPI provenance.
 */
export function toMigrationSql(p: CpiProjection): string {
  const src = `EA2025 cl 25.1 — ${p.effectiveFrom} increase (CPI ${p.cpiPercent}% + 0.5%)`;
  const rateValues = p.rates
    .map(
      (r) =>
        `    ('${p.effectiveFrom}','${r.classification}','${r.employmentBasis}',` +
        `${money(r.ordinaryHourlyRate)},${money(r.paidHourlyRate)},${q(src)})`,
    )
    .join(',\n');
  const allowanceValues = p.allowances
    .map((a) => `    ('${p.effectiveFrom}','${a.code}',${money(a.amount)},'${a.unit}',${q(src)})`)
    .join(',\n');

  return `-- ${src}
-- Generated by the Phase-2 rate admin UI. Review against the published ABS CPI
-- before applying, and mirror into RATE_SCHEDULE (see the TS snippet). cl 25.3:
-- verify rates stay >= 2% above the Amusement, Events & Recreation Award.
INSERT INTO "public"."eba_rate"
    ("effective_from","classification","employment_basis","ordinary_hourly_rate","paid_hourly_rate","source")
VALUES
${rateValues}
ON CONFLICT ("effective_from","classification","employment_basis") DO NOTHING;

INSERT INTO "public"."eba_allowance"
    ("effective_from","code","amount","unit","source")
VALUES
${allowanceValues}
ON CONFLICT ("effective_from","code") DO NOTHING;`;
}

/**
 * Emit the one-line TS snippet that appends the same increase to the embedded
 * RATE_SCHEDULE via `applyCpiIncrease` (keeps the worker engine in sync). The
 * index is the position of the base set in RATE_SCHEDULE.
 */
export function toRateScheduleSnippet(p: CpiProjection, baseIndex = 0): string {
  const label = `ICC Sydney EA 2025 — ${p.effectiveFrom} increase (CPI + 0.5%, cl 25.1)`;
  return (
    `// Add to src/modules/rosters/domain/projections/utils/cost/rate-schedule.ts\n` +
    `RATE_SCHEDULE.push(applyCpiIncrease(\n` +
    `  RATE_SCHEDULE[${baseIndex}],\n` +
    `  ${p.cpiPercent}, // ABS All-Groups CPI (Sydney), March-quarter YoY % (cl 25.2)\n` +
    `  '${p.effectiveFrom}',\n` +
    `  '${label}',\n` +
    `));`
  );
}
