import { supabase } from '@/platform/realtime/client';

/**
 * Demand Engine L9 — demand_templates read/write queries.
 *
 * Table: public.demand_templates (migration 20260502000014).
 * Templates are reusable named shift-sets keyed on a ClusterKey tuple.
 * Auto-generated by templateBuilder.service once a cluster reaches K=10 events.
 */

export interface ClusterKey {
    event_type: string | null;
    pax_band: '<100' | '100-300' | '300-600' | '600-1500' | '1500+';
    service_type: string | null;
    alcohol: boolean | null;
    room_count_band: '1' | '2-3' | '4+';
}

export interface TemplateShiftCell {
    slice_idx: number;
    function_code: string;
    level: number;
    headcount: number;
    sample_size: number;
}

export interface DemandTemplateRow {
    id: string;
    template_code: string;
    cluster_key: ClusterKey;
    shifts: TemplateShiftCell[];
    source_event_ids: string[];
    is_seeded: boolean;
    is_active: boolean;
    superseded_by: string | null;
    created_by: string | null;
    created_at: string;
    updated_at: string;
}

export interface TemplateInput {
    template_code: string;
    cluster_key: ClusterKey;
    shifts: TemplateShiftCell[];
    source_event_ids: string[];
    is_seeded?: boolean;
}

export const demandTemplatesQueries = {
    /** Return all currently active templates, newest first. */
    async listActive(): Promise<DemandTemplateRow[]> {
        const { data, error } = await supabase
            .from('demand_templates')
            .select('*')
            .eq('is_active', true)
            .order('created_at', { ascending: false });
        if (error) throw new Error(`demandTemplates.listActive failed: ${error.message}`);
        return (data ?? []) as unknown as DemandTemplateRow[];
    },

    /**
     * Find the first active template whose cluster_key contains all fields of
     * the given ClusterKey (JSONB @> containment via `.contains()`).
     * Returns null when no match exists.
     */
    async findByClusterKey(clusterKey: ClusterKey): Promise<DemandTemplateRow | null> {
        const { data, error } = await supabase
            .from('demand_templates')
            .select('*')
            .eq('is_active', true)
            .contains('cluster_key', clusterKey as unknown as Record<string, unknown>)
            .order('created_at', { ascending: false })
            .limit(1)
            .maybeSingle();
        if (error) throw new Error(`demandTemplates.findByClusterKey failed: ${error.message}`);
        return data as unknown as DemandTemplateRow | null;
    },

    /**
     * Insert a new template or update the existing row with the same
     * template_code (unique constraint). Returns the persisted row.
     */
    async upsert(input: TemplateInput): Promise<DemandTemplateRow> {
        const { data, error } = await supabase
            .from('demand_templates')
            .upsert(
                {
                    template_code: input.template_code,
                    cluster_key: input.cluster_key as unknown as Record<string, unknown>,
                    shifts: input.shifts as unknown as Record<string, unknown>[],
                    source_event_ids: input.source_event_ids,
                    is_seeded: input.is_seeded ?? false,
                    updated_at: new Date().toISOString(),
                },
                { onConflict: 'template_code' },
            )
            .select('*')
            .single();
        if (error) throw new Error(`demandTemplates.upsert failed: ${error.message}`);
        return data as unknown as DemandTemplateRow;
    },

    /** Soft-retire a template by id (set is_active = false). */
    async deactivate(id: string): Promise<void> {
        const { error } = await supabase
            .from('demand_templates')
            .update({ is_active: false, updated_at: new Date().toISOString() })
            .eq('id', id);
        if (error) throw new Error(`demandTemplates.deactivate failed: ${error.message}`);
    },
};
