-- Load 374 ICC Sydney catalogue roles across 14 departments
WITH catalogue_roles (dept_name, subdept_name, role_name, eba_min, eba_max, salaried, def_level) AS (
  VALUES
  ('Executive Office', 'Executive Leadership', 'Chief Executive Officer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Executive Leadership', 'Deputy Chief Executive Officer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Executive Leadership', 'Chief Financial Officer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Executive Leadership', 'Chief People Officer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Executive Leadership', 'General Manager – Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Executive Support & Reception', 'Executive Assistant to the CEO', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Executive Support & Reception', 'Executive Assistant to the General Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Executive Support & Reception', 'Corporate Receptionist', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Executive Office', 'Executive Support & Reception', 'Administration Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Executive Office', 'Legal & Compliance', 'Senior Manager, Legal & Compliance', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Legal & Compliance', 'Legal Counsel', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Quality Assurance', 'Senior Manager, Quality Systems', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Quality Assurance', 'Quality Assurance Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Executive Office', 'Quality Assurance', 'Quality Assurance Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Business Development', 'Leadership & Admin', 'Director of Business Development', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Leadership & Admin', 'Senior Manager, Business Development', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Leadership & Admin', 'Executive Assistant to the Director', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Leadership & Admin', 'Assistant to the Director', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Corporate', 'BD Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Corporate', 'BD Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Corporate', 'BD Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Business Development', 'National Conventions', 'BD Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'National Conventions', 'BD Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'National Conventions', 'BD Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Business Development', 'International Conventions', 'BD Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'International Conventions', 'BD Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'International Conventions', 'BD Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Business Development', 'Exhibitions', 'BD Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Exhibitions', 'BD Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Exhibitions', 'BD Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Business Development', 'Partnerships', 'Manager, BD & Partnerships', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Partnerships', 'BD & Partnerships Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Partnerships', 'Business Events Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Research & Insights', 'Research & Insights Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Research & Insights', 'Research Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Research & Insights', 'Research Team Leader', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Research & Insights', 'Research Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Research & Insights', 'Research Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Business Development', 'Revenue & Yield', 'Revenue & Yield Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Revenue & Yield', 'Senior Business Analyst', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Business Development', 'Revenue & Yield', 'Business Analyst', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Leadership & Admin', 'Director of Events', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Leadership & Admin', 'Events Administration Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Events', 'Event Planning', 'Senior Manager, Event Planning', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Planning', 'Event Planning Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Planning', 'Senior Event Planner', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Planning', 'Event Planner', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Planning', 'Event Planning Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Events', 'Event Planning', 'Event Planning Intern', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Events', 'Event Management', 'Senior Event Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Management', 'Event Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Management', 'Event Services Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Events', 'Event Management', 'Event Services Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Events', 'Event Management', 'Event Services Trainee', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Events', 'Event Management', 'Event Services Graduate', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Events', 'Event Management', 'UTS Event Management Graduate', 2::smallint, 3::smallint, false::boolean, 3::smallint),
  ('Events', 'Event Operations', 'Senior Manager, Event Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Operations', 'Manager, Event Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Operations', 'Event Operations Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Operations', 'Senior Event Services Floor Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Operations', 'Event Services Floor Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Operations', 'Venue Manager (The Cutaway)', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Operations', 'Floor Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Events', 'Event Operations', 'Event Operations Coordinator', 4::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Events', 'Exhibition Services', 'Exhibition Floor Manager', 6::smallint, 7::smallint, false::boolean, 6::smallint),
  ('Events', 'Exhibition Services', 'Exhibition Services Supervisor', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('Events', 'Exhibition Services', 'Exhibition Services Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Events', 'Exhibition Services', 'Exhibition Services Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Events', 'Event Setup', 'Manager, Event Setup', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Setup', 'Assistant Manager, Event Setup', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Events', 'Event Setup', 'Event Setup Supervisor', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Events', 'Event Setup', 'Event Setup Coordinator', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('Events', 'Event Setup', 'Event Setup Team Leader', 4::smallint, 4::smallint, false::boolean, 4::smallint),
  ('Events', 'Event Setup', 'Event Setup Team Member', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Event Delivery', 'Leadership & Admin', 'Director of Event Delivery', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Leadership & Admin', 'Senior Manager, Event Delivery', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Leadership & Admin', 'Manager, Event Delivery', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'Senior Event Delivery Manager', 6::smallint, 7::smallint, true::boolean, 7::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'Event Delivery Manager', 6::smallint, 7::smallint, true::boolean, 6::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'Assistant Event Delivery Manager', 6::smallint, 6::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'F&B Senior Floor Manager', 6::smallint, 7::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'F&B Floor Manager', 6::smallint, 7::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'Assistant F&B Floor Manager', 5::smallint, 6::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'Event Delivery Supervisor', 6::smallint, 7::smallint, false::boolean, NULL::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'F&B Supervisor', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'F&B Team Leader', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'F&B Team Member', 1::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Event Delivery', 'Event Food & Beverage', 'F&B Intern', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Senior Manager, Retail & Beverage Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Retail Services Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Senior Event Delivery Manager', 6::smallint, 7::smallint, true::boolean, 7::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Event Delivery Manager', 6::smallint, 7::smallint, true::boolean, 6::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Assistant Event Delivery Manager', 6::smallint, 6::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Senior Retail Services Floor Manager', 6::smallint, 7::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Retail Services Floor Manager', 6::smallint, 7::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Event Delivery Supervisor', 6::smallint, 7::smallint, false::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Retail Services Supervisor', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Laneway Bar Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Café Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Beverage Supervisor', 6::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Event Delivery', 'Retail & Beverage', 'Beverage Team Leader', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Event Delivery', 'F&B Coordination', 'Assistant F&B Services Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Event Delivery', 'F&B Coordination', 'F&B Services Coordinator', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Event Delivery', 'F&B Coordination', 'Event Delivery Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Event Delivery', 'F&B Coordination', 'Casual F&B Coordinator – Rostering', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('Culinary Services', 'Leadership & Admin', 'Director of Culinary Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Leadership & Admin', 'Executive Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Leadership & Admin', 'Food Safety & Kitchen Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Leadership & Admin', 'Assistant to the Director', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Leadership & Admin', 'Culinary Project Administrator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Culinary Services', 'Leadership & Admin', 'Senior Kitchen Administration Assistant', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Culinary Services', 'Leadership & Admin', 'Kitchen Administration Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Executive Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Chef de Cuisine', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Senior Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Junior Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Chef de Partie', 7::smallint, 7::smallint, false::boolean, 7::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Demi Chef', 6::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Commis Chef', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Chef', 4::smallint, 4::smallint, false::boolean, 4::smallint),
  ('Culinary Services', 'Events & Catering Kitchen', 'Apprentice Chef', 1::smallint, 4::smallint, false::boolean, 1::smallint),
  ('Culinary Services', 'Production Kitchen', 'Sous Chef – Larder', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Production Kitchen', 'Sous Chef – Sauce', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Production Kitchen', 'Junior Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Production Kitchen', 'Chef de Partie', 7::smallint, 7::smallint, false::boolean, 7::smallint),
  ('Culinary Services', 'Pastry', 'Executive Pastry Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Pastry', 'Senior Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Pastry', 'Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Pastry', 'Junior Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Pastry', 'Chef de Partie', 7::smallint, 7::smallint, false::boolean, 7::smallint),
  ('Culinary Services', 'Pastry', 'Demi Chef', 6::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Culinary Services', 'Pastry', 'Apprentice Cook', 1::smallint, 3::smallint, false::boolean, 1::smallint),
  ('Culinary Services', 'Retail Outlets Kitchen', 'Executive Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Retail Outlets Kitchen', 'Sous Chef', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Kitchen Logistics Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Chief Steward', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Senior Kitchen Logistics Supervisor', 6::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Senior Steward Supervisor', 6::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Kitchen Logistics Supervisor', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Steward Supervisor', 6::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Kitchen Logistics Team Leader', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Steward Team Leader', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Culinary Services', 'Kitchen Logistics & Stewarding', 'Steward', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Audio Visual Services', 'Leadership & Admin', 'Director of AV Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'Leadership & Admin', 'Senior Manager, AV Production', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'Leadership & Admin', 'Assistant to the Director', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'Leadership & Admin', 'AV Operations Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Audio Visual Services', 'Leadership & Admin', 'Production Administration Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Audio Visual Services', 'AV Sales & Project Management', 'Senior Manager, AV Business Development', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Sales & Project Management', 'Sales Manager – AV', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Sales & Project Management', 'Senior AV Project Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Sales & Project Management', 'AV Project Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Sales & Project Management', 'CAD Planner', 4::smallint, 6::smallint, false::boolean, 4::smallint),
  ('Audio Visual Services', 'AV Floor Operations', 'AV Floor Manager', 6::smallint, 7::smallint, false::boolean, 6::smallint),
  ('Audio Visual Services', 'AV Technical', 'Senior AV Technical Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Technical', 'AV Technical Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Technical', 'AV Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Technical', 'Audio Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Technical', 'Vision Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Technical', 'Vision Supervisor', 5::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Audio Visual Services', 'AV Technical', 'Lighting Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Technical', 'Senior Systems Technician', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Audio Visual Services', 'AV Technical', 'Senior AV Technician', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('Audio Visual Services', 'AV Technical', 'AV Technician', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('Audio Visual Services', 'AV Technical', 'AV/ICT Support Technician', 3::smallint, 4::smallint, false::boolean, 4::smallint),
  ('Audio Visual Services', 'Rigging', 'Rigging Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'Rigging', 'Rigging Technician', 4::smallint, 6::smallint, false::boolean, 4::smallint),
  ('Audio Visual Services', 'Staging & Production Crew', 'Staging & Sets Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'Staging & Production Crew', 'AV Staging Team Leader', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Audio Visual Services', 'Staging & Production Crew', 'AV Production Crew', 1::smallint, 7::smallint, false::boolean, 2::smallint),
  ('Audio Visual Services', 'Staging & Production Crew', 'AV Graduate', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Audio Visual Services', 'Staging & Production Crew', 'AV Graduate Trainee', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Audio Visual Services', 'Staging & Production Crew', 'Screen & Media Trainee', 0::smallint, 1::smallint, false::boolean, NULL::smallint),
  ('Audio Visual Services', 'Digital Media & Signage', 'Digital Media Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'Digital Media & Signage', 'Digital Signage Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Audio Visual Services', 'Digital Media & Signage', 'Digital Signage Designer', 4::smallint, 6::smallint, false::boolean, 4::smallint),
  ('Audio Visual Services', 'Digital Media & Signage', 'Digital Signage Coordinator', 4::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Audio Visual Services', 'Digital Media & Signage', 'Digital Senior Technician', 5::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Live Entertainment', 'Leadership & Admin', 'Director of Live Entertainment', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Leadership & Admin', 'Senior Manager, Live Events', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Leadership & Admin', 'Assistant to the Director', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Leadership & Admin', 'Events Administration Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Live Entertainment', 'Live Event Management', 'Live Events Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Live Event Management', 'Senior Event Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Live Event Management', 'Event Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Live Event Management', 'Live Events Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Live Entertainment', 'Live Event Management', 'Live Events Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Live Entertainment', 'Live Event Operations', 'Manager, Live Event Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Live Event Operations', 'Live Production Trainee', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Live Entertainment', 'Ticketing, Bookings & Merchandise', 'Manager, Ticketing & Bookings', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Ticketing, Bookings & Merchandise', 'Merchandise Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Ticketing, Bookings & Merchandise', 'Ticketing & Bookings Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Live Entertainment', 'Ticketing, Bookings & Merchandise', 'Ticketing & Bookings Coordinator', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('Live Entertainment', 'Ticketing, Bookings & Merchandise', 'Merchandise Supervisor', 4::smallint, 4::smallint, false::boolean, 4::smallint),
  ('Live Entertainment', 'Ticketing, Bookings & Merchandise', 'Merchandise Team Leader', 3::smallint, 3::smallint, false::boolean, 3::smallint),
  ('Live Entertainment', 'Ticketing, Bookings & Merchandise', 'Merchandise Team Member', 2::smallint, 2::smallint, false::boolean, 2::smallint),
  ('Customer Services', 'Leadership & Admin', 'Senior Manager, Customer Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Customer Services', 'Leadership & Admin', 'Manager, Customer Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Customer Services', 'Customer Service', 'Senior Customer Service Coordinator', 4::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Customer Services', 'Customer Service', 'Customer Service Coordinator', 4::smallint, 4::smallint, false::boolean, 4::smallint),
  ('Customer Services', 'Customer Service', 'Customer Service Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Customer Services', 'Customer Service', 'Customer Service Team Leader', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('Customer Services', 'Customer Service', 'Customer Service Team Member', 1::smallint, 2::smallint, false::boolean, 2::smallint),
  ('Customer Services', 'Ushering', 'Team Leader Usher', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('Customer Services', 'Ushering', 'Usher', 1::smallint, 1::smallint, false::boolean, 1::smallint),
  ('Building Services', 'Leadership & Admin', 'Director of Building Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Leadership & Admin', 'Executive Assistant to the Directors of Building Services & Security', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Leadership & Admin', 'Administration Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Building Services', 'Assets & Trades', 'Senior Manager, Assets & Trades', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Assets & Trades', 'Assets & Trades Services Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Assets & Trades', 'Assistant Manager, Assets & Trades', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Assets & Trades', 'Assets & Trades Supervisor', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('Building Services', 'Assets & Trades', 'Trade Services Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Building Services', 'Assets & Trades', 'Electrician', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Building Services', 'Assets & Trades', 'Handyperson', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('Building Services', 'Assets & Trades', 'Building Services Team Member', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Building Services', 'Assets & Trades', 'Building Services Intern', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Building Services', 'FM Interface & Contact Centre', 'Interface Manager – FM Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'FM Interface & Contact Centre', 'Assistant Manager, Interface – FM Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'FM Interface & Contact Centre', 'Contact Centre Supervisor', 6::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Building Services', 'FM Interface & Contact Centre', 'Contact Centre Team Leader', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Building Services', 'FM Interface & Contact Centre', 'Contact Centre Team Member', 2::smallint, 5::smallint, false::boolean, 2::smallint),
  ('Building Services', 'Car Park & Logistics', 'Senior Manager, Car Park & Logistics', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Car Park & Logistics', 'Assistant Manager, Car Park & Logistics', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Car Park & Logistics', 'Manager, Event Logistics', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Car Park & Logistics', 'Car Park & Logistics Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Building Services', 'Car Park & Logistics', 'Event Logistics Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Building Services', 'Car Park & Logistics', 'Traffic Logistics Supervisor', 5::smallint, 6::smallint, false::boolean, NULL::smallint),
  ('Building Services', 'Car Park & Logistics', 'Logistics Administrator', 3::smallint, 4::smallint, false::boolean, NULL::smallint),
  ('Building Services', 'Car Park & Logistics', 'Dock Controller', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Building Services', 'Car Park & Logistics', 'Car Park & Logistics Team Member', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Building Services', 'Car Park & Logistics', 'Loading Dock Team Member', 3::smallint, 3::smallint, false::boolean, 3::smallint),
  ('Building Services', 'Car Park & Logistics', 'Car Park Attendant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Building Services', 'Presentation Services', 'Senior Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Presentation Services', 'Presentation Services Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Presentation Services', 'Assistant Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Building Services', 'Presentation Services', 'Presentation Services Supervisor', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Building Services', 'Presentation Services', 'Presentation Services Team Leader', 4::smallint, 4::smallint, false::boolean, 4::smallint),
  ('Building Services', 'Presentation Services', 'Cleaner Team Leader', 4::smallint, 4::smallint, false::boolean, NULL::smallint),
  ('Building Services', 'Presentation Services', 'Presentation Services Team Member', 1::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Building Services', 'Presentation Services', 'Cleaner', 1::smallint, 3::smallint, false::boolean, 1::smallint),
  ('Building Services', 'Presentation Services', 'Administration Assistant', 1::smallint, 2::smallint, false::boolean, NULL::smallint),
  ('Building Services', 'Uniform Room', 'Uniform Room Supervisor', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Building Services', 'Uniform Room', 'Uniform Room Team Member', 2::smallint, 4::smallint, false::boolean, 2::smallint),
  ('Security & Risk', 'Leadership & Admin', 'Senior Manager, Security Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Leadership & Admin', 'Security Operations Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Leadership & Admin', 'Security Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Leadership & Admin', 'Security Administration Officer', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Security & Risk', 'Building Security', 'Building Security Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Building Security', 'Assistant Building Security Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Building Security', 'Security Supervisor', 6::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Security & Risk', 'Building Security', 'Security Team Leader', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Security & Risk', 'Building Security', 'Security Officer', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('Security & Risk', 'Building Security', 'Security Guard', 3::smallint, 3::smallint, false::boolean, NULL::smallint),
  ('Security & Risk', 'Event Security', 'Event Security Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Event Security', 'Event Security Supervisor', 6::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Security & Risk', 'Event Security', 'Event Security Team Leader', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Security & Risk', 'Security Control Room', 'Control Room Officer', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Security & Risk', 'Security Control Room', 'Control Room Operator', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Security & Risk', 'Risk & WHS', 'Senior Manager, Operational Risk', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Risk & WHS', 'HSE Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Risk & WHS', 'Assistant Manager, Risk', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Risk & WHS', 'Risk Management Systems Advisor', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Security & Risk', 'Risk & WHS', 'Risk & Safety Officer', 4::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Security & Risk', 'Risk & WHS', 'Risk Officer', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Security & Risk', 'Risk & WHS', 'WHS Officer', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('Security & Risk', 'Risk & WHS', 'Risk Officer Trainee', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Security & Risk', 'First Aid', 'Venue First Aid Services Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Security & Risk', 'First Aid', 'First Aid Officer', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('ICT Services', 'Leadership & Admin', 'Director of ICT Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Leadership & Admin', 'Senior Manager, ICT Services', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Leadership & Admin', 'Senior Manager, ICT Service Delivery', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Service Desk & Support', 'ICT Support Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('ICT Services', 'Service Desk & Support', 'Senior ICT Support Technician', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('ICT Services', 'Service Desk & Support', 'ICT Support Technician', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('ICT Services', 'Service Desk & Support', 'ICT Support Analyst', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('ICT Services', 'Service Desk & Support', 'ICT Graduate', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('ICT Services', 'Infrastructure & Network', 'Manager, ICT Infrastructure', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Infrastructure & Network', 'ICT Systems Administrator', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Infrastructure & Network', 'ICT Network Administrator', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Infrastructure & Network', 'Network Engineer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Infrastructure & Network', 'ICT Infrastructure Support Engineer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'ICT Event & Venue Operations', 'Manager, ICT Event Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'ICT Event & Venue Operations', 'Manager, ICT Venue Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'ICT Event & Venue Operations', 'Supervisor, ICT Event Operations', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('ICT Services', 'ICT Event & Venue Operations', 'Supervisor, ICT Venue Operations', 5::smallint, 6::smallint, false::boolean, 6::smallint),
  ('ICT Services', 'Solutions & Applications', 'ICT Solutions Delivery Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Solutions & Applications', 'Technical Innovation Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Solutions & Applications', 'Business Systems Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Solutions & Applications', 'ICT Solutions Delivery Specialist', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Solutions & Applications', 'Application Support Specialist', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Solutions & Applications', 'System Analyst', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Solutions & Applications', 'AI Solutions Developer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Event Information Systems', 'EIS Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Event Information Systems', 'EIS Specialist', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('ICT Services', 'Event Information Systems', 'EIS Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Finance & Administration', 'Leadership & Admin', 'Director of Finance & Administration', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Financial Controller', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Finance Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Accountant', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Management Accountant', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Financial Systems Accountant', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Assistant Accountant', 4::smallint, 6::smallint, false::boolean, 4::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Auditor', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Financial Accounting & Reporting', 'Finance Intern', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Senior Accounts Officer', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Credit Controller', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Cash Room Supervisor', 5::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Accounts Officer', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Junior Accounts Officer', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Accounts Officer Trainee', 0::smallint, 1::smallint, false::boolean, 0::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Accounts Payable Assistant', 2::smallint, 3::smallint, false::boolean, NULL::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Accounts Receivable Assistant', 2::smallint, 3::smallint, false::boolean, NULL::smallint),
  ('Finance & Administration', 'Accounts Payable & Receivable', 'Accounts Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Finance & Administration', 'Payroll', 'Payroll Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Payroll', 'Senior Payroll Officer', 5::smallint, 6::smallint, false::boolean, 6::smallint),
  ('Finance & Administration', 'Payroll', 'Payroll Officer', 3::smallint, 4::smallint, false::boolean, 4::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'Procurement Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'Purchasing Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'Assistant Procurement Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'FF&E & Contracts Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'FF&E & Asset Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'Inventory Controller', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'Purchasing Officer', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'Stores Supervisor', 5::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Finance & Administration', 'Procurement & Stores', 'Storeperson', 2::smallint, 2::smallint, false::boolean, 2::smallint),
  ('People & Culture', 'Leadership & Admin', 'Director of Human Resources', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Leadership & Admin', 'Executive Assistant to the Chief People Officer', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Leadership & Admin', 'Manager, Diversity, Equity & Inclusion', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'People Partnering', 'Senior Manager, People Partnering', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'People Partnering', 'Senior Business Partner', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'People Partnering', 'Business Partner', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'People Partnering', 'Employee Relations Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'Senior Manager, People Operations', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'HR Shared Services Advisor', 4::smallint, 5::smallint, false::boolean, 5::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'HR Shared Services Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'People Operations Coordinator', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'HR Coordinator', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'Systems & Reporting Specialist', 4::smallint, 6::smallint, false::boolean, 6::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'People Operations Administrator', 3::smallint, 4::smallint, false::boolean, 3::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'People & Culture Administrator', 3::smallint, 4::smallint, false::boolean, NULL::smallint),
  ('People & Culture', 'People Operations & Shared Services', 'HR Administrator', 2::smallint, 3::smallint, false::boolean, 2::smallint),
  ('People & Culture', 'Talent Acquisition', 'Talent Acquisition Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Talent Acquisition', 'Talent Acquisition Advisor', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Learning & Development', 'L&D Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Learning & Development', 'L&D Specialist', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Learning & Development', 'L&D Advisor', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Learning & Development', 'L&D Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('People & Culture', 'Learning & Development', 'L&D Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('People & Culture', 'Workforce Planning', 'Manager, Event Workforce', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Workforce Planning', 'Supervisor, Event Workforce', 5::smallint, 6::smallint, false::boolean, 5::smallint),
  ('People & Culture', 'Workforce Planning', 'Workforce Planning Advisor', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('People & Culture', 'Workforce Planning', 'Event Workforce Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('People & Culture', 'Workforce Planning', 'Workforce Planning Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Corporate Affairs & Communications', 'Leadership & Admin', 'Director of Corporate Affairs', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Leadership & Admin', 'Director of Communications', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Leadership & Admin', 'Corporate Affairs & Communications Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Leadership & Admin', 'Executive Assistant to the Director', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Leadership & Admin', 'Assistant to the Director', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Marketing & Communications', 'Marketing & Communications Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Marketing & Communications', 'Marketing & Communications Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Marketing & Communications', 'Marketing & Communications Coordinator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Corporate Affairs & Communications', 'Marketing & Communications', 'Marketing Coordinator', 4::smallint, 5::smallint, false::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Marketing & Communications', 'Media Coordinator', 4::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Corporate Affairs & Communications', 'Marketing & Communications', 'Marketing Assistant', 1::smallint, 2::smallint, false::boolean, 1::smallint),
  ('Corporate Affairs & Communications', 'Marketing & Communications', 'Communications Assistant', 1::smallint, 2::smallint, false::boolean, 2::smallint),
  ('Corporate Affairs & Communications', 'Digital & Design', 'Senior Digital Marketing Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Digital & Design', 'Digital Marketing Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Digital & Design', 'Digital Content Creator', 4::smallint, 5::smallint, false::boolean, 4::smallint),
  ('Corporate Affairs & Communications', 'Digital & Design', 'Graphic Designer', 4::smallint, 5::smallint, false::boolean, 5::smallint),
  ('Corporate Affairs & Communications', 'Corporate Social Responsibility', 'CSR Manager', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Corporate Social Responsibility', 'CSR Executive', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint),
  ('Corporate Affairs & Communications', 'Corporate Social Responsibility', 'Architectural Communications Consultant', NULL::smallint, NULL::smallint, true::boolean, NULL::smallint)
)
INSERT INTO hr.roles (subdepartment_id, name, eba_level_min, eba_level_max, typically_salaried, remuneration_level, is_active, created_at, updated_at)
SELECT
  s.id,
  cr.role_name,
  cr.eba_min,
  cr.eba_max,
  cr.salaried,
  cr.def_level,
  true,
  now(),
  now()
FROM catalogue_roles cr
JOIN hr.departments d ON d.name = cr.dept_name
JOIN hr.subdepartments s ON s.department_id = d.id AND s.name = cr.subdept_name
ON CONFLICT (subdepartment_id, name) DO UPDATE SET
  eba_level_min = EXCLUDED.eba_level_min,
  eba_level_max = EXCLUDED.eba_level_max,
  typically_salaried = EXCLUDED.typically_salaried,
  remuneration_level = EXCLUDED.remuneration_level,
  is_active = EXCLUDED.is_active,
  updated_at = now();
