-- 1. Drop dependent view
DROP VIEW IF EXISTS shifts_with_state;

-- 2. Drop legacy columns
ALTER TABLE shifts DROP COLUMN IF EXISTS status;
ALTER TABLE shifts DROP COLUMN IF EXISTS bidding_deadline;
ALTER TABLE shifts DROP COLUMN IF EXISTS bidding_start_at;
ALTER TABLE shifts DROP COLUMN IF EXISTS bidding_end_at;

-- 3. Recreate View (Updated Schema)
CREATE OR REPLACE VIEW shifts_with_state AS
SELECT 
    id,
    roster_id,
    department_id,
    sub_department_id,
    role_id,
    shift_date,
    start_time,
    end_time,
    break_minutes,
    total_hours,
    -- status removed
    notes,
    is_recurring,
    recurrence_rule,
    confirmed_at,
    created_at,
    updated_at,
    assignment_id,
    organization_id,
    remuneration_level_id,
    actual_hourly_rate,
    bidding_close_at,
    bidding_enabled,
    bidding_open_at,
    is_draft,
    shift_group_id,
    shift_subgroup_id,
    version,
    created_by_user_id,
    last_modified_by,
    last_modified_reason,
    deleted_at,
    deleted_by,
    roster_date,
    template_id,
    template_group,
    template_sub_group,
    is_from_template,
    template_instance_id,
    group_type,
    sub_group_name,
    display_order,
    role_level,
    remuneration_rate,
    currency,
    cost_center_id,
    scheduled_start,
    scheduled_end,
    is_overnight,
    scheduled_length_minutes,
    net_length_minutes,
    paid_break_minutes,
    unpaid_break_minutes,
    timezone,
    assigned_employee_id,
    assigned_at,
    is_cancelled,
    cancelled_at,
    cancelled_by_user_id,
    cancellation_reason,
    is_on_bidding,
    bidding_priority_text,
    trade_requested_at,
    required_skills,
    required_licenses,
    eligibility_snapshot,
    event_ids,
    tags,
    compliance_snapshot,
    compliance_checked_at,
    compliance_override,
    compliance_override_reason,
    is_published,
    published_at,
    published_by_user_id,
    is_locked,
    lock_reason_text,
    timesheet_id,
    actual_start,
    actual_end,
    actual_net_minutes,
    payroll_exported,
    cancelled_by,
    required_certifications,
    event_tags,
    -- bidding legacy columns removed
    user_contract_id,
    assignment_status,
    fulfillment_status,
    offer_expires_at,
    is_urgent,
    attendance_status,
    assignment_outcome,
    bidding_status,
    trading_status,
    lifecycle_status,
    get_shift_state_id(lifecycle_status, assignment_status, assignment_outcome, bidding_status, trading_status) AS state_id
FROM shifts s;
